import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import ResponsiveHeader from './ResponsiveHeader'
import { useEffect, useRef, useState } from 'react'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faGithub, faLinkedin, faLinkedinIn } from '@fortawesome/free-brands-svg-icons' 
import { faChevronCircleDown } from '@fortawesome/free-solid-svg-icons'

const inter = Inter({ subsets: ['latin'] })

const navValues = ['home', 'about', 'resume', 'work', 'contact'];

export default function Home() {

  const [activeLink, setActiveLink] = useState('');
  const homeRef = useRef(null);
  const aboutRef = useRef(null);
  const resumeRef = useRef(null);
  const workRef = useRef(null);
  const contactRef = useRef(null);

  const handleScroll = () => {
    
    if(homeRef.current !== null){
      console.log('home ref', homeRef);
      if(window.pageYOffset > homeRef.current.offsetTop){
        homeRef.current.classList.add('text-green-400');
      }else{
        homeRef.current.classList.remove('text-green-400');
      }
    }
    const sections = document.querySelectorAll('section');
    sections.forEach(section => {
      const sectionTop = section.offsetTop - 50;
      const sectionBottom = sectionTop + section.offsetHeight;
      if (window.scrollY >= sectionTop && window.scrollY < sectionBottom) {
        
        console.log("activeLink", activeLink);
        console.log("id", section.id);
        setActiveLink('#' + section.id);
        console.log('sectionTop', sectionTop);
        console.log('scrollY', scrollY);
        
      }
    });
  };

  useEffect(() => {
    window.addEventListener('scroll', handleScroll);
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);
  
  return (
    <>
      <Head>
        <title>Omar Alktan | Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section ref={homeRef} id="home" className="w-full h-[800px] min-h-[500px] bg-cover bg-start"
      style={{ backgroundImage: `url('/images/sky.jpg')` }}>
        <div className='hidden'>
          <Image 
            src="/images/sky.jpg"
            alt='mountains'
            layout='fill'
            objectFit='cover'
            quality={100}
          />
        </div>
        <nav id="nav-header" className={`fixed ${activeLink !== '#home' && activeLink !== '' ? 'bg-[#130406]' : ''} top-0 py-2 left-0 w-full z-10`}>
            <ul className='flex justify-center'>
              {navValues.map(value=>{
                return (
                  <li key={value} className={` ${activeLink === `#${value}` ? `text-green-400` : `text-white`}  text-center text-sm font-semibold tracking-custom flex-row px-3 py-2 uppercase cursor-pointer`}>
                    <a href={`#${value}`}>{value}</a>
                  </li>
                )
              })}
            </ul>
        </nav>
        <div id="header-content" className='pt-[10%] '>
          <div className='w-2xl mx-auto'>
            <ResponsiveHeader />
            <div className='max-w-2xl m-auto'>
              <h3 className='text-center pt-8 text-xl font-thinner text-[#a8a8a8] w-120 '>
                {"Based in Cairo. "}
                <span className='text-white'>Software Engineer and Polymath</span>. {"I think thoughts others don't so I could do things others won't."}
              </h3>
              <div className='flex gap-10 justify-center mt-14'>
                <a href="https://github.com/OmarAlkttan" target='_blank'>
                  <FontAwesomeIcon className='hover:text-teal-400 transition-colors ease-linear duration-100 cursor-pointer' icon={faGithub} size="2xl" color='white'/> 
                </a>
                <a href="https://www.linkedin.com/in/omar-alktan-948012153/" target='_blank'>
                  <FontAwesomeIcon className='hover:text-teal-400 transition-colors ease-linear duration-100 cursor-pointer' icon={faLinkedinIn} size="2xl" color='white'/>  
                </a>
              </div>
            </div>
            
          </div>
          <div className='text-center mt-20'>

            <a href='#about' >
              <FontAwesomeIcon className='cursor-pointer  mx-auto hover:text-teal-400 transition-colors ease-linear duration-100 ' size='3x' color='white' icon={faChevronCircleDown} />
            </a>
          </div>
          
        </div>
      </section>
      <section id="about" className='h-[600px] bg-green-100' ref={aboutRef}>
        
      </section>
      <section id="resume" className='h-screen bg-red-100' ref={resumeRef}></section>
      <section id="work" className='h-screen bg-blue-100' ref={workRef}></section>
      <section id="contact" className='h-screen bg-gray-100' ref={contactRef}></section>
    </>
  )
}
